"""initial_schema

Revision ID: 5c85006f0eff
Revises: 
Create Date: 2026-03-19 13:40:26.211958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c85006f0eff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('starlink_serial', sa.String(length=100), nullable=True),
    sa.Column('peplink_serial', sa.String(length=100), nullable=True),
    sa.Column('unifi_site_id', sa.String(length=100), nullable=True),
    sa.Column('admin_ssid', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('available', 'deployed', 'maintenance', name='kit_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('admin', 'tech', 'user', name='user_role'), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('shoots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ssid', sa.String(length=32), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('kit_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'active', 'completed', 'cancelled', name='shoot_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shoot_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('starlink_down', 'failover_active', 'ap_offline', 'data_cap_warning', 'high_latency', 'packet_loss', 'custom', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alert_severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_shoot_id'), 'alerts', ['shoot_id'], unique=False)
    op.create_table('billing_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shoot_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('data_gb', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_entries_shoot_id'), 'billing_entries', ['shoot_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('shoot_id', sa.UUID(), nullable=True),
    sa.Column('ap_name', sa.String(length=255), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_mac'), 'devices', ['mac'], unique=False)
    op.create_table('network_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shoot_id', sa.UUID(), nullable=False),
    sa.Column('kit_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('download_mbps', sa.Float(), nullable=False),
    sa.Column('upload_mbps', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('packet_loss', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('starlink', '5g', 'both', name='network_source'), nullable=False),
    sa.Column('is_failover', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_metrics_shoot_id'), 'network_metrics', ['shoot_id'], unique=False)
    op.create_index(op.f('ix_network_metrics_timestamp'), 'network_metrics', ['timestamp'], unique=False)
    op.create_table('roof_telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shoot_id', sa.UUID(), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=False),
    sa.Column('obstruction_pct', sa.Float(), nullable=False),
    sa.Column('tilt_x', sa.Float(), nullable=False),
    sa.Column('tilt_y', sa.Float(), nullable=False),
    sa.Column('compass_heading', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('download_mbps', sa.Float(), nullable=False),
    sa.Column('upload_mbps', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('phone_battery_pct', sa.Float(), nullable=False),
    sa.Column('is_charging', sa.Boolean(), nullable=False),
    sa.Column('source_device', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roof_telemetry_shoot_id'), 'roof_telemetry', ['shoot_id'], unique=False)
    op.create_index(op.f('ix_roof_telemetry_timestamp'), 'roof_telemetry', ['timestamp'], unique=False)
    op.create_table('shoot_accesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('shoot_id', sa.UUID(), nullable=False),
    sa.Column('access_code', sa.String(length=20), nullable=False),
    sa.Column('qr_data', sa.String(length=500), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shoot_accesses_access_code'), 'shoot_accesses', ['access_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shoot_accesses_access_code'), table_name='shoot_accesses')
    op.drop_table('shoot_accesses')
    op.drop_index(op.f('ix_roof_telemetry_timestamp'), table_name='roof_telemetry')
    op.drop_index(op.f('ix_roof_telemetry_shoot_id'), table_name='roof_telemetry')
    op.drop_table('roof_telemetry')
    op.drop_index(op.f('ix_network_metrics_timestamp'), table_name='network_metrics')
    op.drop_index(op.f('ix_network_metrics_shoot_id'), table_name='network_metrics')
    op.drop_table('network_metrics')
    op.drop_index(op.f('ix_devices_mac'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_billing_entries_shoot_id'), table_name='billing_entries')
    op.drop_table('billing_entries')
    op.drop_index(op.f('ix_alerts_shoot_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('shoots')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('kits')
    # ### end Alembic commands ###
